dsn: "sqlite:quickmin.db"
d1Binding: "DB"
r2Bucket: "BUCKET"
jwtSecret: "hvljYEUOLHKqWP8UNxI4HwZvXS6de903"
adminUser: "admin"
adminPass: "admin"
#apiPath: "admin"
upload: "upload"
oauthHostname: localhost

googleClientId: "873713985278-rn59ha657823mq55rdjuslebfbuv3g7q.apps.googleusercontent.com"
googleClientSecret: "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"

collections:
  posts:
    helperText: "Here are some posts..."
    access: admin
    readAccess: public
    fields:
      <Text id="title" fullWidth listable/>
      <Image id="image"/>
      <Reference id="author" reference="users" listable/>
      <Select id="status" choices="draft,published" listable />
      <Date id="published" listable/>
      <RichText id="content" fullWidth/>
      <Json id="jsontest"/>

  pages:
    fields:
      <Text id="slug" listable/>
      <Text id="title" fullWidth listable/>
      <Reference id="author" reference="users" listable/>
      <RichText id="content" fullWidth/>

  users:
    recordRepresentation: name
    fields:
      <Text id="name" username listable/>
      <AuthMethod id="google_auth" provider="google" listable/>
      <Select id="role" choices="user,admin" role listable/>
      <ReferenceMany id="posts" reference="posts" target="author"/>
      <ReferenceMany id="pages" reference="pages" target="author"/>

views:
  my_posts:
    access: user
    from: posts
    where:
      author: ${userId}

  about_me:
    readAccess: user
    single: true
    from: pages
    where:
      author: ${userId}
      slug: about