dsn: "sqlite:quickmin.db"
d1Binding: "DB"
r2Bucket: "BUCKET"
jwtSecret: "hvljYEUOLHKqWP8UNxI4HwZvXS6de903"
adminUser: "admin"
adminPass: "admin"
apiPath: "api"
upload: "upload"

googleClientId: "873713985278-rn59ha657823mq55rdjuslebfbuv3g7q.apps.googleusercontent.com"
googleClientSecret: "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"

roles: [user,admin]

collections:
  posts:
    fields:
      <Text id="title" fullWidth listable/>
      <Image id="image"/>
      <Reference id="author" reference="users" listable/>
      <Select id="status" choices="draft,published" listable />
      <Date id="published" listable/>
      <RichText id="content" fullWidth/>

  pages:
    fields:
      <Text id="slug" listable/>
      <Text id="title" fullWidth listable/>
      <Reference id="author" reference="users" listable/>
      <RichText id="content" fullWidth/>

  users:
    fields:
      <Text id="name" username/>
      <AuthMethod id="google_auth" provider="google"/>
      <RoleSelect id="role"/>

views:
  my_posts:
    from: posts
    where:
      author: ${userId}

  about_me:
    single: true
    from: pages
    where:
      author: ${userId}
      slug: about